### ISSUE TITLE
How to get the confidence image？

### ISSUE THREAD

**Issue by flow-specter** [uwsampa/hfbs#2]
Hi， I've read your code, which is awesome. And I have a question that how you get the confidence image?

**Comment by amritamaz** [comment]
You can use whatever method you like to get the confidence, like the pattern given in the sample dataset or by using domain knowledge to help you estimate a better one. If you are using the [Middlebury Stereo Dataset](url) to evaluate, like we did, you can use the method described [in this supplement](https://drive.google.com/file/d/0B4nuwEMaEsnmdEREcjhlSXM2NGs/view?usp=sharing) to generate a good estimated confidence (see Section 3).
